spring.application.name=demoOfSpringSecurity
#spring.security.user.name=kashish
#spring.security.user.password=payal123

spring.datasource.url=jdbc:mysql://localhost:3307/assignment
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.org.springframework.security=trace

jwt.secret=this-is-kashish-yadav-fullstack-java-developerrr 
jwt.expiration.ms=3600000
spring.security.oauth2.client.registration.github.client-id=Iv23liNftcPtyII7n61m
spring.security.oauth2.client.registration.github.client-secret=4da2d1adc2d2600a825828802e033534fea3c9d6
